export const HOST = "http://localhost:3000";
export const BASE_URL = "http://localhost:8000/api";

export const PLAN_LIMITS = {
  FREE: 0,
  STARTER: 100,
  PRO: 170,
  UNLIMITED: Infinity,
};

export const GLASSDOOR_URLS = {
  "United States": "https://www.glassdoor.com",
  "United Kingdom": "https://www.glassdoor.co.uk",
  Canada: "https://www.glassdoor.ca",
  Australia: "https://www.glassdoor.com.au",
  Germany: "https://www.glassdoor.de",
  France: "https://www.glassdoor.fr",
  Netherlands: "https://www.glassdoor.nl",
  India: "https://www.glassdoor.co.in",
  Singapore: "https://www.glassdoor.sg",
  Nigeria: "https://www.glassdoor.com",
  "South Africa": "https://www.glassdoor.co.za",
  Ireland: "https://www.glassdoor.ie",
  "New Zealand": "https://www.glassdoor.co.nz",
  Remote: "https://www.glassdoor.com",
  Lagos: "https://www.glassdoor.com",
};

export const INDEED_URLS = {
  // Existing countries
  "United States": "https://www.indeed.com/jobs",
  "United Kingdom": "https://uk.indeed.com/jobs",
  Canada: "https://ca.indeed.com/jobs",
  Australia: "https://au.indeed.com/jobs",
  Germany: "https://de.indeed.com/jobs",
  France: "https://fr.indeed.com/jobs",
  Netherlands: "https://nl.indeed.com/jobs",
  India: "https://in.indeed.com/jobs",
  Singapore: "https://sg.indeed.com/jobs",
  Nigeria: "https://ng.indeed.com/jobs",
  "South Africa": "https://za.indeed.com/jobs",
  Ireland: "https://ie.indeed.com/jobs",
  "New Zealand": "https://nz.indeed.com/jobs",
  Remote: "https://www.indeed.com/jobs",
  Lagos: "https://ng.indeed.com/jobs",

  // Added countries
  Spain: "https://es.indeed.com/jobs",
  Italy: "https://it.indeed.com/jobs",
  Japan: "https://jp.indeed.com/jobs",
  Brazil: "https://br.indeed.com/jobs",
  Mexico: "https://mx.indeed.com/jobs",
  Switzerland: "https://ch.indeed.com/jobs",
  Belgium: "https://be.indeed.com/jobs",
  Austria: "https://at.indeed.com/jobs",
  Sweden: "https://se.indeed.com/jobs",
  Norway: "https://no.indeed.com/jobs",
  Denmark: "https://dk.indeed.com/jobs",
  Poland: "https://pl.indeed.com/jobs",
  "United Arab Emirates": "https://ae.indeed.com/jobs",
  "Hong Kong": "https://hk.indeed.com/jobs",
  Malaysia: "https://my.indeed.com/jobs",
  Philippines: "https://ph.indeed.com/jobs",
  Russia: "https://ru.indeed.com/jobs",
  China: "https://cn.indeed.com/jobs",
  "South Korea": "https://kr.indeed.com/jobs",
  Turkey: "https://tr.indeed.com/jobs",

  // More countries
  Argentina: "https://ar.indeed.com/jobs",
  Chile: "https://cl.indeed.com/jobs",
  Colombia: "https://co.indeed.com/jobs",
  Egypt: "https://eg.indeed.com/jobs",
  Finland: "https://fi.indeed.com/jobs",
  Greece: "https://gr.indeed.com/jobs",
  Hungary: "https://hu.indeed.com/jobs",
  Indonesia: "https://id.indeed.com/jobs",
  Israel: "https://il.indeed.com/jobs",
  Kenya: "https://ke.indeed.com/jobs",
  Luxembourg: "https://lu.indeed.com/jobs",
  Morocco: "https://ma.indeed.com/jobs",
  Pakistan: "https://pk.indeed.com/jobs",
  Peru: "https://pe.indeed.com/jobs",
  Portugal: "https://pt.indeed.com/jobs",
  Qatar: "https://qa.indeed.com/jobs",
  Romania: "https://ro.indeed.com/jobs",
  "Saudi Arabia": "https://sa.indeed.com/jobs",
  Taiwan: "https://tw.indeed.com/jobs",
  Thailand: "https://th.indeed.com/jobs",
  Ukraine: "https://ua.indeed.com/jobs",
  Vietnam: "https://vn.indeed.com/jobs",

  // Major cities (already have Lagos)
  London: "https://uk.indeed.com/jobs",
  "New York": "https://www.indeed.com/jobs",
  Tokyo: "https://jp.indeed.com/jobs",
  Paris: "https://fr.indeed.com/jobs",
  Berlin: "https://de.indeed.com/jobs",
  Dubai: "https://ae.indeed.com/jobs",
  Mumbai: "https://in.indeed.com/jobs",
  Sydney: "https://au.indeed.com/jobs",
  Toronto: "https://ca.indeed.com/jobs",
  "São Paulo": "https://br.indeed.com/jobs",
};

export const STATE = {
  IDLE: "idle",
  CHECKING_LOGIN: "checking_login",
  LOGGING_IN: "logging_in",
  NAVIGATING_TO_JOBS: "navigating_to_jobs",
  APPLYING: "applying",
};
